using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OODProject
{
    //generated by postman, used to deserialize the json response from the api call to get class level information
    public class Feature
    {
        public string index { get; set; }
        public string name { get; set; }
        public string url { get; set; }

        public override string ToString()
        {
            return name;
        }
    }

    public class ClassLevel
    {
        public int level { get; set; }
        public int ability_score_bonuses { get; set; }
        public int prof_bonus { get; set; }

        public List<Feature> features { get; set; }

        public Spellcasting spellcasting { get; set; }

        public string index { get; set; }

        public ClassRef @class { get; set; }

        public string url { get; set; }
    }

    public class ClassRef
    {
        public string index { get; set; }
        public string name { get; set; }
        public string url { get; set; }
    }

    public class Spellcasting
    {
        public int cantrips_known { get; set; }
        public int spell_slots_level_1 { get; set; }
        public int spell_slots_level_2 { get; set; }
        public int spell_slots_level_3 { get; set; }
        public int spell_slots_level_4 { get; set; }
        public int spell_slots_level_5 { get; set; }
        public int spell_slots_level_6 { get; set; }
        public int spell_slots_level_7 { get; set; }
        public int spell_slots_level_8 { get; set; }
        public int spell_slots_level_9 { get; set; }
    }

}
