using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OODProject
{
    //generated by postman, used to deserialize the json response from the api call to get class level information
    public class Feature
    {
        public string index { get; set; }
        public string name { get; set; }
        public string url { get; set; }

        public override string ToString()
        {
            return name;
        }
    }

    public class ClassLevel
    {
        public int level { get; set; }
        public int ability_score_bonuses { get; set; }
        public int prof_bonus { get; set; }

        public List<Feature> features { get; set; }

        public string index { get; set; }

        public ClassRef @class { get; set; }

        public string url { get; set; }
    }

    public class ClassRef
    {
        public string index { get; set; }
        public string name { get; set; }
        public string url { get; set; }
    }
}
